const TIMELINE_RACE_GRAPH_DATA = "TIMELINE_RACE_GRAPH_DATA";

const ACTION_TIMELINE_RACE_GRAPH_DATA = (data) => {
  return {
    type: TIMELINE_RACE_GRAPH_DATA,
    data,
  };
};

export default ACTION_TIMELINE_RACE_GRAPH_DATA;
