const FILTERED_DATA_CHANGED_RESET = "FILTERED_DATA_CHANGED_RESET";

const ACTION_FILTERED_DATA_CHANGED_RESET = () => {
  return {
    type: FILTERED_DATA_CHANGED_RESET,
  };
};

export default ACTION_FILTERED_DATA_CHANGED_RESET;
