const TIMELINE_GENDER_GRAPH_DATA = "TIMELINE_GENDER_GRAPH_DATA";

const ACTION_TIMELINE_GENDER_GRAPH_DATA = (data) => {
  return {
    type: TIMELINE_GENDER_GRAPH_DATA,
    data,
  };
};

export default ACTION_TIMELINE_GENDER_GRAPH_DATA;
