const TIMELINE_AGE_GROUP_GRAPH_DATA = "TIMELINE_AGE_GROUP_GRAPH_DATA";

const ACTION_TIMELINE_AGE_GROUP_GRAPH_DATA = (data) => {
  return {
    type: TIMELINE_AGE_GROUP_GRAPH_DATA,
    data,
  };
};

export default ACTION_TIMELINE_AGE_GROUP_GRAPH_DATA;
