const APPLYING_FILTERS_RESET = "APPLYING_FILTERS_RESET";

const ACTION_APPLYING_FILTERS_RESET = () => {
  return {
    type: APPLYING_FILTERS_RESET,
  };
};

export default ACTION_APPLYING_FILTERS_RESET;
