const NEW_YEAR_FINISHED_LOADING_RESET = "NEW_YEAR_FINISHED_LOADING_RESET";

const ACTION_NEW_YEAR_FINISHED_LOADING_RESET = () => {
  return {
    type: NEW_YEAR_FINISHED_LOADING_RESET,
  };
};

export default ACTION_NEW_YEAR_FINISHED_LOADING_RESET;
