const NEW_YEAR_FINISHED_LOADING = "NEW_YEAR_FINISHED_LOADING";

const ACTION_NEW_YEAR_FINISHED_LOADING = () => {
  return {
    type: NEW_YEAR_FINISHED_LOADING,
  };
};

export default ACTION_NEW_YEAR_FINISHED_LOADING;
