const TIMELINE_CATEGORY_GRAPH_DATA = "TIMELINE_CATEGORY_GRAPH_DATA";

const ACTION_TIMELINE_CATEGORY_GRAPH_DATA = (data) => {
  return {
    type: TIMELINE_CATEGORY_GRAPH_DATA,
    data,
  };
};

export default ACTION_TIMELINE_CATEGORY_GRAPH_DATA;
