const TIMELINE_BOROUGH_GRAPH_DATA = "TIMELINE_BOROUGH_GRAPH_DATA";

const ACTION_TIMELINE_BOROUGH_GRAPH_DATA = (data) => {
  return {
    type: TIMELINE_BOROUGH_GRAPH_DATA,
    data,
  };
};

export default ACTION_TIMELINE_BOROUGH_GRAPH_DATA;
